# Site setings
name: 'Aryn'
description: 'vancouver/writer'
# Sidebar about text
site_description: 'vancouver/writer'
logo:
favicon: 'assets/images/favicon.ico'
baseurl:
production_url: https://aryn.ca
disqus: ''
mailchimp_url: ''
# Add your GA Tracking Id
ga_analytics:

# Contact form setings
email: hey@aryn.ca
contact_page_description: "Forma theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter:
facebook: 'aryn.davidson.1'
github:
codepen:
dribbble:
medium:
instagram:
pinterest:
linkedin:

# Navigation
navigation:
  - text: About
    url: /about/
  - text: Style Guide
    url: /style-guide/
  - text: Contact
    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-author-page

# Pagination
paginate: 6
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
